version: '3.7'

# TODO: .env, labels and things aren't applied every "start" only on container creation!?
# TODO: ADD JACKETT https://github.com/Jackett/Jackett

services:
  portal:
    labels:
      - "traefik.frontend.rule=Host:portal.${DOMAIN}"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
      - "traefik.enable=true"
      - "traefik.port=8080"
    container_name: portal
    restart: unless-stopped
    image: traefik:1.7.6-alpine
    command:
      - --docker.domain="${DOMAIN}"
      - --configFile=/etc/traefik/config.toml
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/portal:/etc/traefik:ro
    env_file:
      - .env

  nzbget:
    labels:
      - "traefik.frontend.rule=Host:newz.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=6789"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: nzbget
    restart: unless-stopped
    image: nzbget
    build: ./nzbget
    expose:
      - 6789
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/nzbget:/data
      - ${CONFIG_DIR}/nzbget/downloads:/nzb-downloads
      - ${MEDIA_ROOT}:/myfiles
    env_file:
      - .env

  plex:
    labels:
      - "traefik.frontend.rule=Host:watch.${DOMAIN}"
      - "traefik.port=32400"
      - "traefik.enable=true"
    depends_on:
      - portal
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    expose:
      - 32400
      # - 3005
      # - 8324
      # - 32469
      # - 1900
      # - 32410
      # - 32412
      # - 32413
      # - 32414
    hostname: ${HOSTNAME:-nateflix}
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM:-}
      PLEX_UPDATE_CHANNEL: 8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plex/config:/config
      - /dev/shm:/transcode
      - ${MEDIA_ROOT}:/data:ro
    env_file:
      - .env

  plexstats:
    labels:
      - "traefik.frontend.rule=Host:stats.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=8181"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: plexstats
    restart: unless-stopped
    image: tautulli/tautulli
    expose:
      - 8181
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plexstats:/config
      - ${CONFIG_DIR}/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    env_file:
      - .env

  ombi:
    labels:
      - "traefik.frontend.rule=Host:request.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=5000"
    depends_on:
      - portal
    container_name: ombi
    restart: unless-stopped
    image: ombi
    build: ./ombi
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    expose:
      - 5000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/ombi:/data
    env_file:
      - .env

  sonarr:
    labels:
      - "traefik.frontend.rule=Host:shows.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=8989"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: sonarr
    restart: unless-stopped
    image: sonarr
    build: sonarr
    expose:
      - 8989
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/sonarr:/data
      - ${CONFIG_DIR}/nzbget/downloads:/nzb-downloads
      - ${CONFIG_DIR}/deluge/downloads:/torrent-downloads
      - ${MEDIA_ROOT}:/myfiles
    env_file:
      - .env

  radarr:
    labels:
      - "traefik.frontend.rule=Host:movies.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: radarr
    restart: unless-stopped
    image: radarr
    build: radarr
    expose:
      - 7878
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/radarr:/data
      - ${CONFIG_DIR}/nzbget/downloads:/nzb-downloads
      - ${CONFIG_DIR}/deluge/downloads:/torrent-downloads
      - ${MEDIA_ROOT}:/myfiles
    env_file:
      - .env

  lidarr:
    labels:
      - "traefik.frontend.rule=Host:music.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=8686"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: lidarr
    restart: unless-stopped
    image: lidarr
    build: lidarr
    expose:
      - 8686
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/lidarr:/config
      - ${CONFIG_DIR}/nzbget/downloads:/nzb-downloads
      - ${CONFIG_DIR}/deluge/downloads:/torrent-downloads
      - ${MEDIA_ROOT}:/myfiles
    env_file:
      - .env

  deluge:
    labels:
      - "traefik.frontend.rule=Host:torrents.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=8112"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: deluge
    restart: unless-stopped
    image: deluge
    build: deluge
    environment:
      VPN_REGION: ${VPN_REGION}
    expose:
      - 8112
    dns:
      - 209.222.18.222
      - 209.222.18.218
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/deluge:/data
      - ${CONFIG_DIR}/deluge-web:/data-web
      - ${CONFIG_DIR}/openvpn:/openvpn
      - ${CONFIG_DIR}/deluge/downloads:/torrent-downloads
      - ${MEDIA_ROOT}:/myfiles
    env_file:
      - .env

  # TODO: has issues with systems running resolved, need to figure out a way around this
  # pihole:
  #   restart: unless-stopped
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - 53:53/tcp
  #     - 53:53/udp
  #     - 67:67/udp
  #   expose:
  #     - 80
  #   environment:
  #     # TZ: America/Los_Angeles
  #     WEBPASSWORD: <password>
  #     DNS1: 8.8.8.8
  #     DNS2: 8.8.4.4
  #     # ServerIP: 
  #   volumes:
  #     - /docker/pihole/config:/etc/pihole
  #     - /docker/pihole/dnsmasq:/etc/dnsmasq.d
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
