version: '3.7'

services:
  portal:
    labels:
      - "traefik.frontend.rule=Host:portal.${DOMAIN}"
      - "traefik.port=8080"
    container_name: portal
    restart: unless-stopped
    image: traefik:1.7-alpine
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "8888:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nzbget:
    labels:
      - "traefik.frontend.rule=Host:nzbget.${DOMAIN}"
    container_name: nzbget
    restart: unless-stopped
    image: nzbget
    build: ./nzbget
    environment:
      - TZ=${TZ}
    ports:
      - 6789:6789/tcp
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    #   - ${CONFIG_DIR}/nzbget:/data
    #   - ${DATA_DIR}:/media
    #   - ${NZBGET_SOFTWARE_DIR}:/software
    env_file:
      - .env

  plex:
    labels:
      - "traefik.frontend.rule=Host:plex.${DOMAIN}"
      - "traefik.port=32400"
    container_name: plex
    restart: unless-stopped
    image: plexinc/pms-docker:plexpass
    environment:
      # might need to comment this out
      # - ADVERTISE_IP="http://localhost:32400/"
      - PLEX_UPDATE_CHANNEL=8
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
    #network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plex/config:/config
      - ${CONFIG_DIR}/plex/transcode:/transcode
      - ${CONFIG_DIR}/plex/media:/data
    env_file:
      - .env

  plexstats:
    labels:
      - "traefik.frontend.rule=Host:stats.${DOMAIN}"
    container_name: plexstats
    restart: unless-stopped
    image: tautulli/tautulli
    environment:
      - TZ=${TZ}
    ports:
      - 8181:8181/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plexstats:/config
      - ${CONFIG_DIR}/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    env_file:
      - .env

  ombi:
    labels:
      - "traefik.frontend.rule=Host:request.${DOMAIN}"
    container_name: ombi
    restart: unless-stopped
    image: ombi
    build: ombi
    environment:
      - TZ=${TZ}
    ports:
      - 5000:5000/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/ombi:/data
    env_file:
      - .env

  sonarr:
    labels:
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN}"
    container_name: sonarr
    restart: unless-stopped
    image: sonarr
    build: ./sonarr
    environment:
      - TZ=${TZ}
    ports:
      - 8989:8989/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/sonarr:/data
      - ${DATA_DIR}:/media
    env_file:
      - .env

  radarr:
    labels:
      - "traefik.frontend.rule=Host:radarr.${DOMAIN}"
    container_name: radarr
    restart: unless-stopped
    stop_signal: SIGQUIT
    image: radarr
    build: ./radarr
    environment:
      - TZ=${TZ}
    ports:
      - 7878:7878/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/radarr:/data
      - ${DATA_DIR}:/media
    env_file:
      - .env

  lidarr:
    labels:
      - "traefik.frontend.rule=Host:lidarr.${DOMAIN}"
    container_name: lidarr
    restart: unless-stopped
    stop_signal: SIGQUIT
    image: lidarr
    build: lidarr
    environment:
      - TZ=${TZ}
    ports:
      - 8686:8686/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/nzbget/downloads/completed/Music:/downloads
      - ${CONFIG_DIR}/lidarr:/config
      - /:/myfilesystem
    env_file:
      - .env

  deluge:
    labels:
      - "traefik.frontend.rule=Host:deluge.${DOMAIN}"
    container_name: deluge
    restart: unless-stopped
    image: deluge
    build: deluge
    environment:
      TZ: ${TZ}
      VPN_REGION: US West
    ports:
      - 58846:58846/tcp
      - 8112:8112/tcp
    dns:
      - 209.222.18.222
      - 209.222.18.218
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/deluge:/data
      - ${CONFIG_DIR}/deluge-web:/data-web
      - ${CONFIG_DIR}/openvpn:/openvpn
    env_file:
      - .env

# curl ipinfo.io/ip
