version: '3.7'

# TODO: rename directories to be more constistent
# TODO: add user permissions
# TODO: add torrent "black hole" dir to jackett and deluge
# TODO: make downloaded files go to /media/incoming
# TODO: split out .env files into individual ones so up -d won't restart everything
# TODO: add watchtower https://github.com/v2tec/watchtower
# TODO: watch for pihole update so it can run as non-root user

services:
  portal:
    labels:
      - "traefik.frontend.rule=Host:portal.${DOMAIN}"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
      - "traefik.port=8080"
    container_name: portal
    restart: unless-stopped
    image: traefik:alpine
    user: ${NATEFLIX_UID}:${DOCKER_GID}
    command:
      - --docker.domain=${DOMAIN}
      - "--entryPoints=Name:https Address::8443 TLS"
      - "--entryPoints=Name:http Address::8888 Redirect.EntryPoint:https Redirect.Permanent:true"
      - --defaultentrypoints=http,https
      - --api
      - --retry
      - --metrics
      - --ping
      - --docker
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.watch=true
      - --docker.exposedbydefault=true
      - --configFile=/etc/traefik/config.toml
    ports:
      - ${ADVERTISE_IP}:80:8888/tcp
      - ${ADVERTISE_IP}:443:8443/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/portal:/etc/traefik:ro
    env_file:
      - .env

  jackett:
    labels:
      - "traefik.frontend.rule=Host:jackett.${DOMAIN}"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: jackett
    restart: unless-stopped
    image: linuxserver/jackett:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    networks:
      default:
        aliases:
          - jackett.${DOMAIN}
    expose:
      - 9117
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/jackett:/config
      - ${CONFIG_DIR}/torrents:/downloads
    env_file:
      - .env

  # TODO: Need to configure
  hydra:
    labels:
      - "traefik.frontend.rule=Host:hydra.${DOMAIN}"
      - "traefik.port=5076"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: hydra
    restart: unless-stopped
    image: linuxserver/hydra2
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    networks:
      default:
        aliases:
          - hydra.${DOMAIN}
    expose:
      - 5076
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/hydra:/config
      - ${CONFIG_DIR}/torrents:/downloads
    env_file:
      - .env

  nzbget:
    labels:
      - "traefik.frontend.rule=Host:newz.${DOMAIN}"
      - "traefik.port=6789"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: nzbget
    restart: unless-stopped
    image: linuxserver/nzbget:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    expose:
      - 6789
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/nzbget:/config
      - ${CONFIG_DIR}/downloads/nzbget:/downloads
      - ${MEDIA_ROOT}:/data
    env_file:
      - .env

  plex:
    labels:
      - "traefik.frontend.rule=Host:watch.${DOMAIN}"
      - "traefik.port=32400"
    depends_on:
      - portal
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    ports:
      - ${ADVERTISE_IP}:32400:32400/tcp
      - ${ADVERTISE_IP}:3005:3005/tcp
      - ${ADVERTISE_IP}:8324:8324/tcp
      - ${ADVERTISE_IP}:32469:32469/tcp
      - ${ADVERTISE_IP}:1900:1900/udp
      - ${ADVERTISE_IP}:32410:32410/udp
      - ${ADVERTISE_IP}:32412:32412/udp
      - ${ADVERTISE_IP}:32413:32413/udp
      - ${ADVERTISE_IP}:32414:32414/udp
    expose:
      - 32400
      - 3005
      - 8324
      - 32469
      - 1900
      - 32410
      - 32412
      - 32413
      - 32414
    hostname: ${HOSTNAME:-nateflix}
    devices:
      - /dev/dri
    privileged: true
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM:-}
      PLEX_UPDATE_CHANNEL: 8
      ADVERTISE_IP: https://${ADVERTISE_IP}:32400/
      PLEX_UID: ${NATEFLIX_UID}
      PLEX_GID: ${NATEFLIX_GID}
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plex:/config
      - /dev/shm:/transcode
      - ${MEDIA_ROOT}:/data:ro
    env_file:
      - .env

  plexstats:
    labels:
      - "traefik.frontend.rule=Host:stats.${DOMAIN}"
      - "traefik.port=8181"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: plexstats
    restart: unless-stopped
    image: tautulli/tautulli
    expose:
      - 8181
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/plexstats:/config
      - ${CONFIG_DIR}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    env_file:
      - .env

  ombi:
    labels:
      - "traefik.frontend.rule=Host:request.${DOMAIN}"
      - "traefik.port=3579"
    depends_on:
      - portal
    container_name: ombi
    restart: unless-stopped
    image: linuxserver/ombi:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    expose:
      - 3579
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/ombi:/config
    env_file:
      - .env

  sonarr:
    labels:
      - "traefik.frontend.rule=Host:shows.${DOMAIN}"
      - "traefik.port=8989"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: sonarr
    restart: unless-stopped
    image: linuxserver/sonarr:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    expose:
      - 8989
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/sonarr:/config
      - ${CONFIG_DIR}/downloads:/downloads
      - ${MEDIA_ROOT}/shows:/tv
    env_file:
      - .env

  radarr:
    labels:
      - "traefik.frontend.rule=Host:movies.${DOMAIN}"
      - "traefik.port=7878"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: radarr
    restart: unless-stopped
    image: linuxserver/radarr:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    expose:
      - 7878
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/radarr:/config
      - ${CONFIG_DIR}/downloads:/downloads
      - ${MEDIA_ROOT}/movies:/movies
    env_file:
      - .env

  lidarr:
    labels:
      - "traefik.frontend.rule=Host:music.${DOMAIN}"
      - "traefik.port=8686"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    container_name: lidarr
    restart: unless-stopped
    image: linuxserver/lidarr:latest
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    expose:
      - 8686
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/lidarr:/config
      - ${CONFIG_DIR}/downloads:/downloads
      - ${MEDIA_ROOT}/music:/music
    env_file:
      - .env

  vpn:
    container_name: vpn
    image: qmcgaw/private-internet-access:latest
    cap_add:
      - net_admin
    restart: unless-stopped
    devices:
      - /dev/net/tun
    ports:
      - 58846:58846/tcp
    environment:
      REGION: ${VPN_REGION}
      PROTOCOL: udp
      ENCRYPTION: strong
      USER: ${VPN_USERNAME}
      PASSWORD: ${VPN_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  deluge:
    labels:
      - "traefik.frontend.rule=Host:torrents.${DOMAIN}"
      - "traefik.port=8112"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
      - vpn
    container_name: deluge
    restart: unless-stopped
    image: linuxserver/deluge
    environment:
      PUID: ${NATEFLIX_UID}
      PGID: ${NATEFLIX_GID}
    network_mode: service:vpn
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/deluge:/config
      - ${CONFIG_DIR}/downloads/deluge:/downloads
      - ${CONFIG_DIR}/torrents:/blackhole
      - ${MEDIA_ROOT}/incoming:/data
    env_file:
      - .env

  # TODO: BIG problem for volume permissions! need to make my own container
  pihole:
    labels:
      - "traefik.frontend.rule=Host:pihole.${DOMAIN}"
      - "traefik.port=80"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/users"
    depends_on:
      - portal
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    ports:
      - ${ADVERTISE_IP}:53:53/tcp
      - ${ADVERTISE_IP}:53:53/udp
      - ${ADVERTISE_IP}:67:67/udp
    expose:
      - 80
    environment:
      WEBPASSWORD: ""
      DNS1: 8.8.8.8
      DNS2: 8.8.4.4
      ServerIP: ${ADVERTISE_IP}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.${DOMAIN}
      VIRTUAL_PORT: 443
    volumes:
      - ${CONFIG_DIR}/pihole/config:/etc/pihole
      - ${CONFIG_DIR}/pihole/dnsmasq:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
