#!/usr/bin/env bash

config_file=/config/ServerConfig.json
if [[ ! -f ${config_file} ]]; then
  mono /opt/Jackett/JackettConsole.exe --NoRestart --IgnoreSslErrors=true --NoUpdates --DataFolder=/config --Port 8080 &
  PID=$!
  while [[ ! -f ${config_file} ]]; do
    sleep 1
  done

  kill ${PID}
  wait
fi

if [[ -f ${config_file} ]]; then
  sed -i -e 's/\(^.*"AllowExternal": \).*[^,]\(,\)\{0,1\}$/\1true\2/g' \
      -e 's/\(^.*"Port": \).*[^,]\(,\)\{0,1\}$/\18080\2/g' \
      -e 's/\(^.*"BlackholeDir": \).*[^,]\(,\)\{0,1\}$/\1"\/torrents"\2/g' \
      -e 's/\(^.*"UpdateDisabled": \).*[^,]\(,\)\{0,1\}$/\1true\2/g' \
      -e 's/\(^.*"UpdatePrerelease": \).*[^,]\(,\)\{0,1\}$/\1false\2/g' "${config_file}"
fi

exec /usr/bin/dumb-init --rewrite 15:2 -- "$@"
