#!/usr/bin/env sh

if [ ! -f /config/nzbget.conf ]; then
  echo "[INFO] Copying config into /config/nzbget.conf"
  cp /opt/nzbget/nzbget.conf /config/nzbget.conf
fi

if [ ! -d /config/scripts ]; then
  mkdir -p /config/scripts
fi

exec "$@"
