debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = true


# [frontends]
#   [frontends.portal]
#   backend = "portal"
#   passHostHeader = true
#     [frontends.portal.routes.domain]
#     rule = "Host:portal.nateflix.io"
#
# [backends]
#   [backends.portal]
#   url = "http://portal"

# [acme]
# email = "webmaster@nateflix.io"
# storage = "cert.json"
# entryPoint = "https"
# onHostRule = true
#
# [acme.httpChallenge]
# entryPoint = "http"
