debug = false
logLevel = "INFO"

# defaultEntryPoints = ["https","http"]
#
# [entryPoints]
#   [entryPoints.http]
#   address = ":8888"
#     [entryPoints.http.redirect]
#     entryPoint = "https"
#     permanent = true
#   [entryPoints.https]
#   address = ":8443"
#   [entryPoints.https.tls]

# [retry]
#
# [api]
#
# [ping]
#
# [metrics]

# [docker]
# endpoint = "unix:///var/run/docker.sock"
# watch = true
# exposedByDefault = true


# [frontends]
#   [frontends.portal]
#   backend = "portal"
#   passHostHeader = true
#     [frontends.portal.routes.domain]
#     rule = "Host:portal.nateflix.io"
#
# [backends]
#   [backends.portal]
#   url = "http://portal"

# [acme]
# email = "webmaster@nateflix.io"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# storage = "/etc/traefik/stage.json"
# #caServer = "https://acme-v02.api.letsencrypt.org/directory"
# #storage = "/etc/traefik/cert.json"
# entryPoint = "https"
# [[acme.domains]]
#   sans = [
#     "portal.nateflix.io",
#     "newz.nateflix.io",
#     "torrents.nateflix.io",
#     "watch.nateflix.io",
#     "stats.nateflix.io",
#     "request.nateflix.io",
#     "pihole.nateflix.io",
#     "jackett.nateflix.io",
#     "shows.nateflix.io",
#     "movies.nateflix.io",
#     "music.nateflix.io",
#     "hydra.nateflix.io"
#   ]
#
#   [acme.httpChallenge]
#   entryPoint = "http"
